// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9Wr3DcnqxnEacmXqjZtGigxP5NW7i64M',
    appId: '1:514103970987:web:f138df03e68e923d703bee',
    messagingSenderId: '514103970987',
    projectId: 'flutter-weatherapp-06',
    authDomain: 'flutter-weatherapp-06.firebaseapp.com',
    storageBucket: 'flutter-weatherapp-06.appspot.com',
    measurementId: 'G-431RS87MDX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQkw6vC8phXPQ5TbhN3bdQjEcPeGUDbrQ',
    appId: '1:514103970987:android:380a3e409328718f703bee',
    messagingSenderId: '514103970987',
    projectId: 'flutter-weatherapp-06',
    storageBucket: 'flutter-weatherapp-06.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAWGjun8TWcBbiB78T6w7wtlN5deKc7ko',
    appId: '1:514103970987:ios:9e38983b0f25a195703bee',
    messagingSenderId: '514103970987',
    projectId: 'flutter-weatherapp-06',
    storageBucket: 'flutter-weatherapp-06.appspot.com',
    iosClientId: '514103970987-qpnbq5oi77kl2gftit5n3iv1skv9kvdo.apps.googleusercontent.com',
    iosBundleId: 'com.example.weatherapi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAWGjun8TWcBbiB78T6w7wtlN5deKc7ko',
    appId: '1:514103970987:ios:c7c68dc4aa6e7076703bee',
    messagingSenderId: '514103970987',
    projectId: 'flutter-weatherapp-06',
    storageBucket: 'flutter-weatherapp-06.appspot.com',
    iosClientId: '514103970987-lfiugiklfquas1ph2arnu3m6m6gss9jl.apps.googleusercontent.com',
    iosBundleId: 'com.example.weatherapi.RunnerTests',
  );
}
