name: Flutter Build, Release & Deploy

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set API_KEY in .env
        run: echo "API_KEY=${{ secrets.API_KEY }}" > ${{ github.workspace }}/.env

#       - name: Display .env contents
#         run: cat ${{ github.workspace }}/.env
        
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.3'  # Replace with desired Flutter version

      - name: Install dependencies
        run: flutter pub get

      - name: Set API key as environment variable
        run: echo "API_KEY=${{ secrets.API_KEY }}" >> $GITHUB_ENV

      - name: Build Android and web releases
        run: |
          flutter build apk --release --build-name=${{ github.ref_name }} --build-number=${{ github.run_number }}
          flutter build web --release --base-href "/${{ github.event.repository.name }}/"

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload Android APK
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build/app/outputs/flutter-apk/app-release.apk
          asset_name: weatherapp.apk
          asset_content_type: application/vnd.android.package-archive

      - name: Upload Web Build
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.ACCESS_TOKEN }}
          publish_dir: build/web
